### ISSUE TITLE
Bayeux will not compile with Boost 1.69

### ISSUE THREAD

**Issue by drbenmorgan** [BxCppDev/Bayeux#40]
I've tried out the `develop` branch with current fixes, towards checking that #36 will be satisfied. There are some high level errors in compilation of datatools/serialization due to changes in Boost/Spirit and Boost/Math for 1.69. These reduce to:

```console
/.../Bayeux.git/build/BuildProducts/include/bayeux/datatools/eos/portable_iarchive.hpp:132:10: fatal error: 
      'boost/spirit/home/support/detail/math/fpclassify.hpp' file not found
#include <boost/spirit/home/support/detail/math/fpclassify.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

and similarly in `bayeux/datatools/eos/portable_oarchive.hpp`. This is due, I think to the changes in 1.69 for Boost.Spirit (see the "Spirit" section in https://www.boost.org/users/history/version_1_69_0.html).

I was able to implement a quick and dirty fix to include the right header and namespace for `fpclassify.hpp`, but then ran into cascade errors on missing types:

```console
/.../Bayeux.git/build/BuildProducts/include/bayeux/datatools/eos/portable_iarchive.hpp:415:42: fatal error: 
      no type named 'bits' in 'boost::math::detail::fp_traits_native<double>'
                        typename traits::bits bits;
                        ~~~~~~~~~~~~~~~~~^~~~
```

I haven't gone further because messing around with binary floating points is ☹️ ... This is going to be critical for #30, so needs care.

This was tested on macOS/Clang, and not seen on CentOS7/gcc, *however*, the latter has a system boost install which I suspect is fooling things (and I suspect why this hasn't been picked up yet. It would be helpful if Bayeux had a CI system in place 😒)

**Comment by fmauger** [comment]
Yes you are right. I did not notice this issue for the same reason on ubuntu 18.04.
The boost/spirit/home/support/detail/math/fpclassify.hpp has been removed in 1.69
but system boost install 1.65.1 provides one  and Bayeux builds silently.

**Comment by fmauger** [comment]
I have now a fix using the Boost/Math FP utilities. Seems to work.
I'll do a few more checks before to push the branch for evaluation.

**Comment by drbenmorgan** [comment]
Thanks @fmauger, ping me in this thread once the fixes are pushed and I can test in the SuperNEMO environment.

**Comment by drbenmorgan** [comment]
Resolved as of commit 681b7f31a06d527b78321e2fd79f0b320603cd78, now tracking in #44
