### ISSUE TITLE
Release 3.1.1 Fails to build on macOS/Clang

### ISSUE THREAD

**Issue by drbenmorgan** [BxCppDev/Bayeux#11]
In building release 3.1.1 on macOS for SuperNEMO-DBD/Falaise#82, build failures were detected:

```
[  0%] Building CXX object source/CMakeFiles/Bayeux_mctools_geant4.dir/bxmctools/src/g4/manager_parameters.cc.o
In file included from /Users/tmp/Sandboxes/com.github/supernemo-dbd/bayeux.git/source/bxmctools/src/g4/manager_parameters.cc:21:
In file included from /Users/tmp/Sandboxes/com.github/supernemo-dbd/bayeux.git/build/BuildProducts/include/bayeux/mctools/g4/manager.h:52:
In file included from /Users/tmp/Sandboxes/com.github/supernemo-dbd/bayeux.git/build/BuildProducts/include/bayeux/geomtools/manager.h:48:
/Users/tmp/Sandboxes/com.github/supernemo-dbd/bayeux.git/build/BuildProducts/include/bayeux/datatools/service_tools.h:235:32: fatal error: 'typeid' of incomplete type 'datatools::base_service'
    const std::type_info& tf = typeid(srvc);
                               ^
/Users/bmorgan/Sandboxes/com.github/supernemo-dbd/bayeux.git/build/BuildProducts/include/bayeux/datatools/service_tools.h:51:9: note: forward declaration of 'datatools::base_service'
  class base_service;
        ^
1 error generated.
```

I think this is a regression, original fixed in b06563c6, but reintroduced in 321d3e1. As there have been other changes to those interfaces, I'm not confident that purely reverting the commit will help. Though this is a macOS, I suspect it'll be revealed by Clang on Linux as well. Fundamentally, I believe the issue is GCC being a bit too clever.

A fix is needed before SuperNEMO-DBD/Falaise#82 can be merged.

**Comment by fmauger** [comment]
I think you are right. GCC guess by itself the incomplete typeid.
I have to break this cyclic dep.

**Comment by fmauger** [comment]
Tag Bayeux 3.1.2 (https://github.com/BxCppDev/Bayeux/releases/tag/3.1.2) is ready.

**Comment by drbenmorgan** [comment]
Fixed by 3.1.2 - now testing on Linux platforms.

**Comment by fmauger** [comment]
Have to run additional tests for I have one test that failed on my Linux box.

**Comment by fmauger** [comment]
Should be fix by ea99c5a07.
